# Generated by Django 4.2.7 on 2023-12-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_mymodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartaments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apartament', models.CharField(max_length=255)),
                ('floor', models.IntegerField()),
                ('kvartira', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('dataCreated', models.DateField()),
                ('password', models.CharField(max_length=255)),
                ('countDeal', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
