# Generated by Django 4.2.7 on 2023-12-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_apartaments_id_alter_managers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartaments',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apartaments',
            name='floor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apartaments',
            name='kvartira',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apartaments',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='managers',
            name='countDeal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='managers',
            name='dataCreated',
            field=models.CharField(max_length=255),
        ),
    ]
