# Generated by Django 4.2.7 on 2023-12-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_apartaments_date_alter_apartaments_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartaments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='managers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
