# Generated by Django 4.2.7 on 2023-12-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_apartaments_id_alter_managers_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartaments',
            old_name='kvartira',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='apartaments',
            name='kv',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartaments',
            name='apartament',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartaments',
            name='floor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartaments',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='managers',
            name='countDeal',
            field=models.IntegerField(),
        ),
    ]
