# Generated by Django 4.2.7 on 2023-12-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_apartaments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='dataCreated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
