# Generated by Django 4.2.7 on 2023-12-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_managers_datacreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartaments',
            name='busyUntil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartaments',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
