# Generated by Django 4.2.7 on 2023-12-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_apartaments_busyuntil_apartaments_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='countDeal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
